begin;
insert into auth.users(id) values('00000000-0000-4000-8000-000000000001');
insert into auth.sessions(id,user_id) values('10000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000001');
insert into core.users(id,email) values('00000000-0000-4000-8000-000000000001','admin@example.invalid');
insert into core.events(id,name,active) values('20000000-0000-4000-8000-000000000001','Synthetic',true);
insert into core.user_event_roles values('20000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000001','admin');
insert into core.teams(id,official_id,name,country) values('30000000-0000-4000-8000-000000000001','001','Team A','BR');
create or replace function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'ASSERT: %',label;end if;end$$;
create or replace function pg_temp.expect_error(q text,expected text) returns void language plpgsql as $$begin execute q;raise exception 'EXPECTED_ERROR_NOT_THROWN';exception when others then if sqlerrm<>expected then raise exception 'Expected %, got %',expected,sqlerrm;end if;end$$;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000000001","session_id":"10000000-0000-4000-8000-000000000001"}',true);
select set_config('test.approval',(api.access_grant('{"email":"pending@example.invalid","roles":[],"mode":"add","expectedVersion":0}',gen_random_uuid())->>'entityId'),true);
select pg_temp.assert_true(exists(select 1 from jsonb_array_elements(api.users_list())u where u->>'id'=current_setting('test.approval') and u->>'email'='pending@example.invalid' and u->>'version'='1' and u->'roles'='[]'::jsonb),'pending approval is editable by stable ID and version');
select api.access_grant('{"email":"pending@example.invalid","roles":[],"mode":"add","expectedVersion":1}',gen_random_uuid());
select api.access_grant('{"email":"pending@example.invalid","roles":["filmmaker"],"mode":"replace","expectedVersion":2}',gen_random_uuid());
select pg_temp.assert_true(exists(select 1 from jsonb_array_elements(api.users_list())u where u->>'id'=current_setting('test.approval') and u->>'version'='3' and u->'roles'='["filmmaker"]'::jsonb),'pending replacement reflected in list');
select pg_temp.assert_true(jsonb_array_length(api.users_list(1))=1,'user list applies page bound across pending and active users');
select set_config('test.import',(api.import_preview('{"inputHash":"fixture","columns":["officialId","name","country"],"sheets":["Teams"],"rows":[{"row":1,"officialId":"002","name":"Team B","country":"US","status":"ready","errors":[]},{"row":2,"officialId":"001","name":"Unchanged","country":"BR","status":"ready","errors":[]}]}',gen_random_uuid())->>'entityId'),true);
select api.import_row_commit(jsonb_build_object('previewId',current_setting('test.import'),'row',1,'expectedVersion',1),gen_random_uuid());
select api.import_row_commit(jsonb_build_object('previewId',current_setting('test.import'),'row',2,'expectedVersion',1),gen_random_uuid());
select pg_temp.assert_true(api.import_read(current_setting('test.import')::uuid)->'columns'='["officialId","name","country"]'::jsonb,'preview reload preserves columns');
select pg_temp.assert_true(api.import_read(current_setting('test.import')::uuid)->'sheets'='["Teams"]'::jsonb,'preview reload preserves sheets');
select pg_temp.assert_true(api.import_read(current_setting('test.import')::uuid)->'rows'->0->>'status'='imported','committed preview rows no longer claim ready');
select pg_temp.assert_true(api.import_read(current_setting('test.import')::uuid)->'rows'->1->>'status'='existing','existing row is clearly marked after commit');
select set_config('test.category',(api.category_create('{"name":"TTL fixture"}','40000000-0000-4000-8000-000000000001')->>'entityId'),true);
select set_config('test.item',(api.item_create(jsonb_build_object('categoryId',current_setting('test.category'),'title','Disposable'),gen_random_uuid())->>'entityId'),true);
select pg_temp.assert_true(api.item_delete(jsonb_build_object('itemId',current_setting('test.item'),'expectedVersion',1),gen_random_uuid())->>'outcome'='deleted','delete receipt matches Receipt outcome');
select api.mentor_code_issue(jsonb_build_object('teamId','30000000-0000-4000-8000-000000000001','expectedVersion',0,'digest',repeat('a',64)),gen_random_uuid());
reset role;set local role service_role;
select api.mentor_redeem(repeat('a',64),repeat('b',64));
select api.mentor_device_put(repeat('b',64),'{"installationId":"60000000-0000-4000-8000-000000000001","token":"ExpoPushToken[synthetic]","platform":"android","permission":"granted"}');
reset role;set local role authenticated;
select api.page_create('{"teamId":"30000000-0000-4000-8000-000000000001","sourceArea":"filming","message":"Lease fixture"}',gen_random_uuid());
select pg_temp.assert_true(api.pages_list()->0->>'deliveryStatus'='queued','staff sees queued state');
reset role;set local role service_role;
select set_config('test.delivery',api.delivery_claim()->>0,true);
select pg_temp.assert_true(api.delivery_authorize(current_setting('test.delivery')::uuid)->>'attempt'='1','worker authorization carries lease attempt');
reset role;
update private.deliveries set lease_until=now()-interval '1 second' where id=current_setting('test.delivery')::uuid;
set local role service_role;
select api.delivery_claim();
select pg_temp.assert_true(api.delivery_authorize(current_setting('test.delivery')::uuid)->>'attempt'='2','expired lease is reclaimed with new attempt');
select api.delivery_finish(current_setting('test.delivery')::uuid,false,true,1);
reset role;
select pg_temp.assert_true((select status='leased' from private.deliveries where id=current_setting('test.delivery')::uuid),'stale worker cannot finish new lease');
select pg_temp.assert_true((select bool_and(active) from private.push_devices),'stale worker cannot disable a current token');
set local role service_role;
select api.delivery_finish(current_setting('test.delivery')::uuid,false,true,2);
reset role;set local role authenticated;
select pg_temp.assert_true(api.pages_list()->0->>'deliveryStatus'='failed','provider failure is visible to authorized staff');
reset role;
update private.receipts set expires_at=now()-interval '1 second' where key='40000000-0000-4000-8000-000000000001';
set local role authenticated;
select pg_temp.expect_error($q$select api.category_create('{"name":"TTL fixture"}','40000000-0000-4000-8000-000000000001')$q$,'IDEMPOTENCY_EXPIRED');
reset role;set local role service_role;
select api.purge_due();
reset role;
select pg_temp.assert_true(not exists(select 1 from private.receipts where key='40000000-0000-4000-8000-000000000001'),'worker deletes expired non-Judging receipts');
select pg_temp.assert_true(exists(select 1 from filming.categories where id=current_setting('test.category')::uuid),'receipt cleanup preserves domain state');
rollback;
