-- Apply only to a NEW Supabase project. No legacy operational data is imported.
begin;
create role fgc_command nologin noinherit;
create schema api;
create schema core;
create schema judging;
create schema filming;
create schema messaging;
create schema private;
create schema audit;
revoke all on schema api, core, judging, filming, messaging, private, audit from public;
grant usage on schema api, core, judging, filming, messaging to authenticated;
grant usage on schema api to service_role;
grant usage on schema api, core, judging, filming, messaging, private, audit, auth to fgc_command;
grant select(id,user_id,not_after) on auth.sessions to fgc_command;
grant select(id) on auth.users to fgc_command;
create table core.events(id uuid primary key default gen_random_uuid(), name text not null, active boolean not null default false, schedule_url text check(schedule_url ~ '^https://'), version integer not null default 1);
create unique index one_active_event on core.events(active) where active;
create table core.users(id uuid primary key references auth.users(id), email text not null unique, name text, version integer not null default 1);
create table core.user_event_roles(event_id uuid references core.events, user_id uuid references core.users, role text check(role in ('admin','judge','judgeAdvisor','filmmaker')), primary key(event_id,user_id,role));
create table core.approved_emails(id uuid not null default gen_random_uuid() unique,event_id uuid references core.events, email text, roles text[] not null, version integer not null default 1, primary key(event_id,email), check(roles <@ array['admin','judge','judgeAdvisor','filmmaker']::text[]));
create table core.teams(id uuid primary key default gen_random_uuid(), official_id text not null unique check(length(trim(official_id)) between 1 and 2000), name text not null, country text not null, version integer not null default 1);
create table core.team_pit_locations(event_id uuid references core.events,team_id uuid references core.teams, location text not null, primary key(event_id,team_id));
create table judging.cycles(id uuid primary key default gen_random_uuid(),event_id uuid not null references core.events,state text not null default 'active' check(state in ('active','closed')),version integer not null default 1,closed_at timestamptz,purge_due_at timestamptz,closed_by uuid references core.users,check((state='active' and closed_at is null and purge_due_at is null) or (state='closed' and closed_at is not null and purge_due_at=closed_at+interval '24 hours')));
create unique index one_active_cycle on judging.cycles(event_id) where state='active';
create table judging.panels(id uuid primary key default gen_random_uuid(),cycle_id uuid not null references judging.cycles on delete cascade,name text not null,leader_id uuid not null references core.users,version integer not null default 1,unique(cycle_id,id));
create table judging.members(cycle_id uuid not null,panel_id uuid not null,user_id uuid not null references core.users,version integer not null default 1,primary key(cycle_id,user_id),unique(cycle_id,panel_id,user_id),foreign key(cycle_id,panel_id) references judging.panels(cycle_id,id) on delete cascade);
alter table judging.panels add constraint leader_is_member foreign key(cycle_id,id,leader_id) references judging.members(cycle_id,panel_id,user_id) deferrable initially deferred;
create table judging.participations(id uuid primary key default gen_random_uuid(),cycle_id uuid not null references judging.cycles on delete cascade,team_id uuid not null references core.teams,panel_id uuid,state text not null default 'active' check(state in ('active','withdrawn')),evaluation_state text not null default 'pending' check(evaluation_state in ('pending','evaluated')),has_history boolean not null default false,withdrawal_reason text,version integer not null default 1,unique(cycle_id,team_id),foreign key(cycle_id,panel_id) references judging.panels(cycle_id,id),check(state<>'withdrawn' or length(trim(withdrawal_reason))>0));
create table judging.observations(id uuid primary key default gen_random_uuid(),cycle_id uuid not null,team_id uuid not null,panel_id uuid not null,author_id uuid not null references core.users,notes text not null check(length(notes)<=20000),version integer not null default 1,updated_at timestamptz not null default now(),unique(cycle_id,panel_id,team_id,author_id),foreign key(cycle_id,team_id) references judging.participations(cycle_id,team_id) on delete cascade,foreign key(cycle_id,panel_id) references judging.panels(cycle_id,id));
create table judging.flags(id uuid primary key default gen_random_uuid(),cycle_id uuid not null,team_id uuid not null,type text not null check(type in ('absent','online','other')),reason text,author_id uuid not null references core.users,version integer not null default 1,unique(cycle_id,team_id,type),foreign key(cycle_id,team_id) references judging.participations(cycle_id,team_id) on delete cascade,check(type<>'other' or length(trim(reason))>0));
create table filming.categories(id uuid primary key default gen_random_uuid(),event_id uuid not null references core.events,name text not null check(length(trim(name)) between 1 and 200),description text,version integer not null default 1,unique(event_id,id));
create table filming.items(id uuid primary key default gen_random_uuid(),event_id uuid not null,category_id uuid not null,title text not null check(length(trim(title)) between 1 and 200),done_at timestamptz,done_by uuid references core.users,created_by uuid references core.users,version integer not null default 1,foreign key(event_id,category_id) references filming.categories(event_id,id));
create table filming.templates(id uuid primary key default gen_random_uuid(),event_id uuid not null references core.events,name text not null,description text,required boolean not null default true,unique(event_id,id));
create table filming.shots(id uuid primary key default gen_random_uuid(),event_id uuid not null,template_id uuid not null,team_id uuid not null references core.teams,status text not null check(status in ('pending','captured','skipped')),notes text check(length(notes)<=500),captured_by uuid references core.users,captured_at timestamptz,version integer not null default 1,unique(event_id,template_id,team_id),foreign key(event_id,template_id) references filming.templates(event_id,id));
create table private.mentor_codes(event_id uuid references core.events,team_id uuid references core.teams,digest text not null unique,version integer not null default 1,issued_at timestamptz not null default now(),expires_at timestamptz not null default now()+interval '7 days',primary key(event_id,team_id));
create table private.mentor_sessions(id uuid primary key default gen_random_uuid(),event_id uuid not null,team_id uuid not null,code_version integer not null,token_hash text not null unique,created_at timestamptz not null default now(),expires_at timestamptz not null default now()+interval '7 days',revoked_at timestamptz,foreign key(event_id,team_id) references private.mentor_codes);
create table private.push_devices(id uuid primary key default gen_random_uuid(),session_id uuid not null references private.mentor_sessions,installation_id uuid not null unique,token text not null,platform text not null check(platform in ('ios','android')),active boolean not null default true);
create table messaging.pages(id uuid primary key default gen_random_uuid(),event_id uuid not null references core.events,cycle_id uuid references judging.cycles on delete cascade,team_id uuid not null references core.teams,source_area text not null check(source_area in ('filming','judges')),message text not null check(length(trim(message)) between 1 and 500),sender_id uuid not null references core.users,scheduled_for timestamptz not null default now(),expires_at timestamptz,cancelled_at timestamptz,created_at timestamptz not null default now(),version integer not null default 1,check((source_area='judges')=(cycle_id is not null)));
create table messaging.responses(page_id uuid primary key references messaging.pages on delete cascade,session_id uuid not null references private.mentor_sessions,response text not null,created_at timestamptz not null default now());
create table private.deliveries(id uuid primary key default gen_random_uuid(),page_id uuid not null references messaging.pages on delete cascade,device_id uuid not null references private.push_devices,status text not null default 'queued' check(status in ('queued','leased','accepted','failed','cancelled')),attempts integer not null default 0 check(attempts between 0 and 5),lease_until timestamptz,next_attempt_at timestamptz not null default now(),unique(page_id,device_id));
create table private.receipts(actor_id uuid not null,operation text not null,key uuid not null,payload_hash text not null,result jsonb not null,cycle_id uuid references judging.cycles on delete cascade,expires_at timestamptz not null default now()+interval '24 hours',primary key(actor_id,operation,key));
create table private.closure_intents(id uuid primary key default gen_random_uuid(),cycle_id uuid not null references judging.cycles on delete cascade,actor_id uuid not null references core.users,expires_at timestamptz not null default now()+interval '5 minutes',used_at timestamptz);
create table audit.entries(id uuid primary key default gen_random_uuid(),cycle_id uuid not null references judging.cycles on delete cascade,actor_id uuid not null references core.users,operation text not null,created_at timestamptz not null default now());
create table audit.purge_receipts(purged_at timestamptz not null default now(),routine_version text not null,result text not null check(result in ('success','failure')));
create table private.migration_id_map(source text,entity text,legacy_id text,target_id uuid not null,primary key(source,entity,legacy_id));
-- Restricted command role has only application data privileges, no login or bypassrls.
grant select,insert,update,delete on all tables in schema core,judging,filming,messaging,private,audit to fgc_command;
do $$ declare t record; begin for t in select schemaname,tablename from pg_tables where schemaname in ('core','judging','filming','messaging','private','audit') loop execute format('alter table %I.%I enable row level security',t.schemaname,t.tablename); execute format('alter table %I.%I force row level security',t.schemaname,t.tablename); execute format('create policy command_access on %I.%I to fgc_command using (true) with check (true)',t.schemaname,t.tablename); end loop; end $$;
create function private.actor() returns uuid language plpgsql stable security definer set search_path='' as $$ declare u uuid:=auth.uid(); s uuid; begin
 begin s:=(auth.jwt()->>'session_id')::uuid; exception when others then raise exception 'UNAUTHENTICATED'; end;
 if u is null or s is null or not exists(select 1 from auth.sessions where id=s and user_id=u and (not_after is null or not_after>now())) then raise exception 'UNAUTHENTICATED'; end if;
 if not exists(select 1 from core.users where id=u) then raise exception 'FORBIDDEN'; end if; return u; end $$;
create function private.event_id() returns uuid language sql stable security definer set search_path='' as $$ select id from core.events where active $$;
create function private.has_role(r text) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from core.user_event_roles where user_id=private.actor() and event_id=private.event_id() and role=r) $$;
create function private.require_role(r text) returns uuid language plpgsql security definer set search_path='' as $$ begin if not (private.has_role(r) or (r='filmmaker' and private.has_role('admin'))) or (r in ('judge','judgeAdvisor') and private.has_role('admin')) then raise exception 'FORBIDDEN'; end if; return private.actor(); end $$;
create function private.judging_access(c uuid,p uuid default null) returns boolean language sql stable security definer set search_path='' as $$ select not private.has_role('admin') and exists(select 1 from judging.cycles where id=c and event_id=private.event_id() and state='active') and (private.has_role('judgeAdvisor') or (private.has_role('judge') and exists(select 1 from judging.members where cycle_id=c and panel_id=p and user_id=private.actor()))) $$;
create function private.lock_cycle() returns uuid language plpgsql security definer set search_path='' as $$ declare c uuid; begin if private.has_role('admin') or not (private.has_role('judgeAdvisor') or private.has_role('judge')) then raise exception 'FORBIDDEN'; end if; select id into c from judging.cycles where event_id=private.event_id() and state='active' for update; if c is null then raise exception 'STATE_CONFLICT'; end if; return c; end $$;
create function private.replay(a uuid,op text,k uuid,p jsonb) returns jsonb language plpgsql security definer set search_path='' as $$ declare r private.receipts; begin if k is null then raise exception 'VALIDATION_ERROR'; end if; perform pg_advisory_xact_lock(hashtextextended(a::text||op||k::text,0)); select * into r from private.receipts where actor_id=a and operation=op and key=k; if found then if r.expires_at<=clock_timestamp() then raise exception 'IDEMPOTENCY_EXPIRED';end if;if r.payload_hash<>encode(sha256(convert_to(p::text,'UTF8')),'hex') then raise exception 'DUPLICATE'; end if; return r.result; end if; return null; end $$;
create function private.receipt(a uuid,op text,k uuid,p jsonb,i uuid,v integer,c uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$ declare r jsonb:=jsonb_build_object('commandId',k,'entityId',i,'resultingVersion',v,'outcome',case when op like '%delete' or op='participation_remove' then 'deleted' when v=1 then 'created' else 'updated' end,'committedAt',now()); begin insert into private.receipts(actor_id,operation,key,payload_hash,result,cycle_id) values(a,op,k,encode(sha256(convert_to(p::text,'UTF8')),'hex'),r,c); if c is not null then insert into audit.entries(cycle_id,actor_id,operation) values(c,a,op); end if; return r; end $$;
create function private.assert_version(actual integer,expected integer) returns void language plpgsql set search_path='' as $$ begin if expected is null or actual<>expected then raise exception 'VERSION_CONFLICT'; end if; end $$;
-- Function ownership and grants are finalized after all RPC definitions.
commit;



